spring:
  h2:
    console:
      enabled: true
   
  profiles:
      active: test 
         
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:callcenter;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
      
server:
  port: 9096